- name: installing lamp-stack on ubuntu
  hosts: all
  become: true
  tasks:
    - name: installing apache2
      ansible.builtin.apt:
        update_cache: yes
        name: apache2
        state: present
    - name: installing php
      ansible.builtin.apt:
        name: php libapache2-mod-php php-mysql
        state: present
        