- name: installing lamp-stack on ubuntu
  hosts: all
  become: true
  tasks:
    - name: installing apache2
      ansible.builtin.apt:
        update_cache: yes
        name: apache2
        state: present
    - name: installing php
      ansible.builtin.apt:
        name: php
        state: present
    - name: installing php
      ansible.builtin.apt:
        name: libapache2-mod-php
        state: present
    - name: installing php
      ansible.builtin.apt:
        name: php-mysql
        state: present
    - name: creating info.php file
      ansible.builtin.copy:
        src: info.php
        dest: info.php