- name: install nop-commerce
  hosts: all
  become: yes
  vars:
    microsoft_package_deb: "https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb"
    apt_https_transport: apt-transport-https
    asp_netcore_runtime: aspnetcore-runtime-7.0
  tasks:
    - name: download microsoft package
      ansible.builtin.command: "wget {{ microsoft_package_deb }}"
    - name: install microsoft_package_deb
      ansible.builtin.dpkg_selections:
        name: packages-microsoft-prod.deb
        selection: install
    - name: install .net core runtime
      ansible.builtin.package:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - "{{ apt_https_transport }}"
        - "{{ asp_netcore_runtime }}"
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: run nginx service
      ansible.builtin.systemd:
        name: nginx
        state: started
    - name: modify reverse proxy
      ansible.builtin.file:
        src: default
        dest: "/etc/nginx/sites-available/default"
        state: file
    - name: create a directory
      ansible.builtin.file:
        dest: /var/www/nopCommerce
        state: directory
    - name: install 
      ansible.builtin.unarchive:
        src: "https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.1/nopCommerce_4.60.1_NoSource_linux_x64.zip"
        dest: /var/www/nopCommerce
        remote_src: yes
    - name: create bin directory
      ansible.builtin.file:
        dest: /var/www/nopCommerce/bin
        state: directory
    - name: create logs directory
      ansible.builtin.file:
        dest: /var/www/nopCommerce/logs
        state: directory
    - name: changing permissions
      ansible.builtin.file:
        src: /var/www/nopCommerce
        owner: www-data
        group: www-data 
        state: directory
    - name: create nopcommerce service
      ansible.builtin.file:
        src: nopCommerce.service
        dest: "/etc/systemd/system/nopCommerce.service"
        state: touch
    - name: run nginx service
      ansible.builtin.systemd:
        name: nopCommerce.service
        state: started
      notify: 
        - restart nginx
  handlers:
    - name: restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted