- name: installing tomcat for multi-distro
  hosts: all
  become: yes
  tasks:
    - name: installing jdk-11
      ansible.builtin.package:
        name: "{{ java_package_name }}"
        state: present
    - name: create group
      ansible.builtin.group:
        name: "{{ group_name }}"
        state: present
    - name: create user
      ansible.builtin.user:
        create_home: yes
        group: "{{ group_name }}"
        home: "{{ user_home }}"
        name: "{{ user_name }}"
        shell: "{{ shell }}"
        state: present
    - name: adding stat
      ansible.builtin.stat:
        path: "{{ user_home }}/latest/bin/startup.sh"
        register: file_data
    - name: downloading tomcat
      ansible.builtin.unarchive:
        src: "https://www-eu.apache.org/dist/tomcat/tomcat-{{ tomcat_major_version }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz" 
        dest: "{{ user_home }}"
        remote_src: true
        group: "{{ group_name }}"
      when: not file_data.stat.exists
    - name: adding links
      ansible.builtin.file:
        src: "{{ user_home }}/apache-tomcat-{{ tomcat_version }}"
        path: "{{ user_home }}/latest"
        state: link
    - name: changing ownership
      ansible.builtin.file:
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
        path: "{{ user_home }}"
        recurse: true
        state: directory
    - name: executing script
      ansible.builtin.command:
        cmd: "sudo sh -c 'chmod +x {{ user_home }}/latest/bin/*.sh'"
    - name: creating system D unit file
      ansible.builtin.copy:
        src: ubuntu.tomcat.service
        dest: "/etc/systemd/system/{{ service_name }}"
        group: "{{ user_name }}"
        owner: "{{ group_name }}"
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: creating system D unit file
      ansible.builtin.copy:
        src: centos.tomcat.service
        dest: "/etc/systemd/system/{{ service_name }}"
        group: "{{ user_name }}"
        owner: "{{ group_name }}"
      when: ansible_facts['distribution'] == "CentOS"
    - name: daemon reload and starting tomcat service
      ansible.builtin.systemd:
        daemon_reload: true
        name: "{{ service_name }}"
        state: started
