- name: install utilities
  hosts: all
  become: yes
  vars:
    packages:
      - git
      - unzip
      - tree
  tasks:
    - name: install utils
      ansible.builtin.package:
        name: "{{ packages }}"
        update_cache: yes
        state: present
      notify:
        - ensure ssh is running
  handlers:
    - name: ensure ssh is running
      ansible.builtin.systemd:
        name: sshd
        state: running