- name: install tomcat on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: jdk install
      ansible.builtin.apt:
        update_cache: yes
        name: openjdk-11-jdk
        state: present
    - name: create group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: create user
      ansible.builtin.user:
        create_home: yes
        group: tomcat
        home: /opt/tomcat
        name: tomcat
        shell: /bin/false
        state: present
    - name: downloading tomcat
      ansible.builtin.unarchive:
        src: https://www-eu.apache.org/dist/tomcat/tomcat-10/v10.1.4/bin/apache-tomcat-10.1.4.tar.gz 
        dest: /opt/tomcat
        remote_src: true
        group: tomcat
    - name: adding links
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-10.1.4
        path: /opt/tomcat/latest
        state: link
    - name: changing ownership
      ansible.builtin.file:
        owner: tomcat
        group: tomcat
        path: /opt/tomcat
        recurse: true
        state: directory
