- name: install tomcat on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: jdk install
      ansible.builtin.apt:
        update_cache: yes
        name: openjdk-11-jdk
        state: present
    - name: create group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: create user
      ansible.builtin.user:
        create_home: yes
        group: tomcat
        home: /opt/tomcat
        name: tomcat
        shell: /bin/false
        state: present