- name: install tomcat on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: jdk install
      ansible.builtin.apt:
        update_cache: yes
        name: openjdk-11-jdk
        state: present
    - name: create group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: create user
      ansible.builtin.user:
        create_home: yes
        group: tomcat
        home: /opt/tomcat
        name: tomcat
        shell: /bin/false
        state: present
    - name: downloading tomcat
      ansible.builtin.unarchive:
        remote_src: yes
        src: https://www-eu.apache.org/dist/tomcat/tomcat-10/v${VERSION}/bin/apache-tomcat-${VERSION}.tar.gz 
        dest: /opt/tomcat