---
# tasks file for saymyname
- name: installing apache2
  ansible.builtin.package:
    update_cache: yes
    name: "{{ apache_package }}"
    state: present
- name: installing php-packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ php_packages }}"
- name: checking info.php file
  ansible.builtin.stat:
    path: /var/www/html/info.php
  register: info
- name: creating info.php file
  ansible.builtin.copy:
    src: info.php
    dest: /var/www/html/info.php
  when: not info.stat.exists 
